---
title: "UCSB IAS Comps"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 30px;">
<div class="col-sm-6">

# **Contributors**

The past and present graduate students listed below have contributed resources so that those who follow may benefit from previous triumphs and mistakes! Website last updated: `r Sys.Date()`.

## Carmen Hove
Website Manager\
UCSB tenture: 2015-Present\
Email: carmenhove@ucsb.edu \
GitHub: carmenhove\  
Comps Topics: Developmental Origins of Human Health & Disease | Human Reproductive Ecology | Human-Pathogen Co-Evolution
 
## Angela Garcia 
UCSB tenure: 2013-2018\
Email: garsmol@gmail.com\
Comps Topics: Stress, Immune Function and Inequality | Evolutionary Medicine/Human Biology | Human Behavioral Ecology/Life History Theory 

## Ronnie Bailey-Steinitz
UCSB tenure: 2016-Present\
Email: rsteinitz@ucsb.edu\
Comps Topics: Primate Energetics / Endocrinology | Evolutionary adaptations to seasonal and prolonged nutritional stress | Primate Behavioral & Community Ecology

## Melanie Martin
UCSB tenure: 2008-2015\
Email: martinm7@uw.edu\
Comps Topics: Biosocial evolution | Culture | Human Behavioral Ecology | Health and Disease | Life History Theory | Human Reproduction

## Tiffany Pan
UCSB tenure: 2019-Present (comps taken at UW)\
Email: tdpan@ucsb.edu\
Comps Topics: Demographic and Epidemiological Transition | Evolutionary Medicine | Life History Theory | Population Genetics

## Amy Anderson
UCSB tenure: 2015-Present\
Email: anderson.amy.susan@gmail.com\
Comps Topics: Host-pathogen co-evolution | Demographic (Neolithic) transition | Developmental Origins and Human Health and Disease
