---
title: "Advice + Tips"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

The UCSB IAS comprehensive exam, while often seemingly shrowded in mystery, is the first major hurdle you must clear during your graduate career. It's a 3-day writing marathon, during which time you will be asked to exemplify your (1) mastery of the available literature on general topics AND your chosen specializations and (2) ability to critically assess said literature. Here are our tips from experience with comps. 

# Start early

It's impossible to successfully cram for this exam, so start early and work gradually. Build up an outline for general anthropology and each of your specialization topics (which you should clear with your advisor beforehand). Add relevant info that you may glean from papers/books/lectures/conferences. 

# Sort PDFs and citations

Keeping PDFs and citations organized, accessible, and tabulated is a must. Use Mendeley (more info under Links section) or other PDF organizer to sort papers and citations. And make sure you install a citation plug-in inside Word. 
